name: Build and Push Docker Image

on:
  push:
    branches:
      # - mai
  pull_request:
    branches:
      # - mai

env:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  # AWS region
  AWS_REGION: us-east-2

jobs:
  build:
    name: "Apply source code changes"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python (for Ansible)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3

    - name: Run Ansible Playbook to Deploy EC2 and Go App
      run: ansible-playbook -i inventory run_deploy.yaml
